-- Day 13 — AI Phone v2: voice cloning + Cal.com booking + outbound calling
--
-- Layered on top of Day 12 phone schema:
--   * phone_assistants gains voice_provider + voice_id + booking_provider + cal_com_*
--   * phone_voices: per-org cloned voices (ElevenLabs voice_id)
--   * phone_bookings: appointments scheduled via the AI during a call
--   * phone_campaigns: outbound call campaigns (review requests, NPS, custom)
--   * phone_campaign_targets: one row per outbound call attempt

-- ============================================================
-- Extend phone_assistants for voice + booking config
-- ============================================================
ALTER TABLE phone_assistants
  ADD COLUMN IF NOT EXISTS voice_provider       text NOT NULL DEFAULT 'twilio',
  ADD COLUMN IF NOT EXISTS elevenlabs_voice_id  text,
  ADD COLUMN IF NOT EXISTS elevenlabs_model     text DEFAULT 'eleven_turbo_v2_5',
  ADD COLUMN IF NOT EXISTS booking_provider     text,         -- 'cal_com' | 'google_calendar' | null
  ADD COLUMN IF NOT EXISTS cal_com_api_key_ct   bytea,        -- encrypted Cal.com API key
  ADD COLUMN IF NOT EXISTS cal_com_iv           bytea,
  ADD COLUMN IF NOT EXISTS cal_com_event_type   integer,      -- Cal.com event type ID for booking
  ADD COLUMN IF NOT EXISTS booking_buffer_min   integer NOT NULL DEFAULT 60;

ALTER TABLE phone_assistants
  ADD CONSTRAINT phone_assistants_voice_provider_chk
    CHECK (voice_provider IN ('twilio','elevenlabs'));

-- ============================================================
-- phone_voices — per-org cloned voices
-- ============================================================
CREATE TABLE phone_voices (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  provider             text NOT NULL DEFAULT 'elevenlabs',
  external_voice_id    text NOT NULL,                          -- ElevenLabs voice_id
  display_name         text NOT NULL,
  description          text,
  source_sample_url    text,                                    -- URL of the original audio sample
  preview_audio_url    text,                                    -- short preview generated by provider
  status               text NOT NULL DEFAULT 'active',          -- active | failed | deleted
  created_at           TIMESTAMP(3) NOT NULL DEFAULT now(),
  CONSTRAINT phone_voices_provider_chk CHECK (provider IN ('elevenlabs')),
  CONSTRAINT phone_voices_status_chk CHECK (status IN ('active','failed','deleted')),
  CONSTRAINT phone_voices_external_uniq UNIQUE (organization_id, external_voice_id)
);
CREATE INDEX idx_phone_voices_org ON phone_voices(organization_id, status);

ALTER TABLE phone_voices ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_voices FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON phone_voices
  USING       (organization_id = (SELECT app.current_org()))
  WITH CHECK  (organization_id = (SELECT app.current_org()));


-- ============================================================
-- phone_bookings — appointments scheduled during AI calls
-- ============================================================
CREATE TABLE phone_bookings (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  call_id              uuid NOT NULL REFERENCES phone_calls(id) ON DELETE CASCADE,
  provider             text NOT NULL,                          -- cal_com | google_calendar
  external_booking_id  text,
  attendee_name        text,
  attendee_email       text,
  attendee_phone       text,
  start_at             TIMESTAMP(3) NOT NULL,
  end_at               TIMESTAMP(3),
  timezone             text DEFAULT 'UTC',
  status               text NOT NULL DEFAULT 'pending',         -- pending | confirmed | cancelled | rescheduled
  notes                text,
  created_at           TIMESTAMP(3) NOT NULL DEFAULT now(),
  CONSTRAINT phone_bookings_provider_chk CHECK (provider IN ('cal_com','google_calendar')),
  CONSTRAINT phone_bookings_status_chk CHECK (status IN ('pending','confirmed','cancelled','rescheduled'))
);
CREATE INDEX idx_phone_bookings_org ON phone_bookings(organization_id, start_at DESC);

ALTER TABLE phone_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_bookings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON phone_bookings
  USING       (organization_id = (SELECT app.current_org()))
  WITH CHECK  (organization_id = (SELECT app.current_org()));


-- ============================================================
-- phone_campaigns — outbound calling campaigns
-- ============================================================
CREATE TABLE phone_campaigns (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  phone_number_id      uuid REFERENCES phone_numbers(id) ON DELETE SET NULL,
  name                 text NOT NULL,
  purpose              text NOT NULL,                          -- review_request | nps_survey | win_back | custom
  status               text NOT NULL DEFAULT 'draft',          -- draft | running | paused | completed | failed
  script               text,                                    -- the AI's opening hook
  call_window_start    time NOT NULL DEFAULT '09:00',           -- local time
  call_window_end      time NOT NULL DEFAULT '20:00',
  call_window_timezone text NOT NULL DEFAULT 'America/New_York',
  call_window_days     text[] NOT NULL DEFAULT ARRAY['mon','tue','wed','thu','fri'],
  rate_per_minute      integer NOT NULL DEFAULT 5,              -- max simultaneous calls
  total_targets        integer NOT NULL DEFAULT 0,
  completed_targets    integer NOT NULL DEFAULT 0,
  failed_targets       integer NOT NULL DEFAULT 0,
  scheduled_for        TIMESTAMP(3),
  started_at           TIMESTAMP(3),
  completed_at         TIMESTAMP(3),
  created_at           TIMESTAMP(3) NOT NULL DEFAULT now(),
  updated_at           TIMESTAMP(3) NOT NULL DEFAULT now(),
  CONSTRAINT phone_campaigns_purpose_chk
    CHECK (purpose IN ('review_request','nps_survey','win_back','custom')),
  CONSTRAINT phone_campaigns_status_chk
    CHECK (status IN ('draft','running','paused','completed','failed'))
);
CREATE INDEX idx_phone_campaigns_org ON phone_campaigns(organization_id, status, scheduled_for);

ALTER TABLE phone_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_campaigns FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON phone_campaigns
  USING       (organization_id = (SELECT app.current_org()))
  WITH CHECK  (organization_id = (SELECT app.current_org()));


-- ============================================================
-- phone_campaign_targets — one row per outbound call attempt
-- ============================================================
CREATE TABLE phone_campaign_targets (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id          uuid NOT NULL REFERENCES phone_campaigns(id) ON DELETE CASCADE,
  organization_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  to_e164              text NOT NULL,
  attendee_name        text,
  context              jsonb,                                    -- arbitrary metadata: review_id, order_id, etc.
  call_id              uuid REFERENCES phone_calls(id) ON DELETE SET NULL,
  attempts             integer NOT NULL DEFAULT 0,
  status               text NOT NULL DEFAULT 'queued',          -- queued | calling | completed | failed | skipped
  scheduled_for        TIMESTAMP(3) NOT NULL DEFAULT now(),
  last_attempted_at    TIMESTAMP(3),
  completed_at         TIMESTAMP(3),
  consent_attested_at  TIMESTAMP(3),                            -- TCPA compliance
  failure_reason       text,
  CONSTRAINT phone_campaign_targets_status_chk
    CHECK (status IN ('queued','calling','completed','failed','skipped'))
);
CREATE INDEX idx_phone_campaign_targets_due ON phone_campaign_targets(status, scheduled_for) WHERE status = 'queued';
CREATE INDEX idx_phone_campaign_targets_campaign ON phone_campaign_targets(campaign_id, status);

ALTER TABLE phone_campaign_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE phone_campaign_targets FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON phone_campaign_targets
  USING       (organization_id = (SELECT app.current_org()))
  WITH CHECK  (organization_id = (SELECT app.current_org()));


-- ============================================================
-- Grants
-- ============================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON phone_voices            TO app_tenant_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON phone_bookings          TO app_tenant_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON phone_campaigns         TO app_tenant_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON phone_campaign_targets  TO app_tenant_user;
