import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getOrgContext } from "@/lib/auth/org-context";
import { withTenant } from "@/lib/db/with-tenant";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AppShellServer } from "@/components/app-shell-server";
import { TopBar } from "@/components/topbar";
import { PageHeader } from "@/components/page-header";

export const dynamic = "force-dynamic";

export default async function PhoneCallDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const { orgId } = await getOrgContext();

  const call = await withTenant(orgId, async (tx) =>
    tx.phoneCall.findFirst({
      where: { id },
      include: {
        turns: { orderBy: { turnNumber: "asc" } },
      },
    }),
  );
  if (!call) notFound();

  return (
    <AppShellServer topBar={<TopBar title="Call detail" />}>
      <PageHeader
        title="Call detail"
        description="Full transcript + lead info."
        breadcrumb={[{"label":"AI Phone","href":"/phone"},{"label":"Call"}]}
      />

        
      <div className="space-y-6">
<Card>
          <CardHeader>
            <CardTitle className="text-base">Call info</CardTitle>
          </CardHeader>
          <CardContent>
            <dl className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Status</dt>
                <dd className="capitalize">{call.status.replace(/-/g, " ")}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">To</dt>
                <dd className="font-mono">{call.toE164}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Intent</dt>
                <dd>{call.intent ?? "—"}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Caller location</dt>
                <dd>{[call.callerState, call.callerCountry].filter(Boolean).join(", ") || "—"}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">AI cost</dt>
                <dd>${(call.aiCostMicros / 1_000_000).toFixed(4)}</dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Turns</dt>
                <dd>{call.aiTotalTurns}</dd>
              </div>
            </dl>
            {(call.leadName || call.leadEmail || call.leadPhone) && (
              <div className="mt-4 rounded-md bg-emerald-50 border border-emerald-200 p-3 text-sm">
                <div className="font-medium text-emerald-900 mb-1">Lead captured</div>
                {call.leadName && <div>Name: {call.leadName}</div>}
                {call.leadEmail && <div>Email: {call.leadEmail}</div>}
                {call.leadPhone && <div>Phone: {call.leadPhone}</div>}
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">Transcript ({call.turns.length} turns)</CardTitle>
            <CardDescription>Caller speech transcribed by Twilio; assistant responses generated by Claude.</CardDescription>
          </CardHeader>
          <CardContent>
            {call.turns.length === 0 ? (
              <p className="text-sm text-muted-foreground">No transcript captured.</p>
            ) : (
              <ul className="space-y-3">
                {call.turns.map((t) => (
                  <li
                    key={t.id}
                    className={`rounded-md p-3 ${
                      t.role === "caller" ? "bg-slate-100" : "bg-indigo-50 border border-indigo-100"
                    }`}
                  >
                    <div className="flex items-center justify-between text-xs">
                      <span className="font-medium capitalize">{t.role}</span>
                      {t.confidence && (
                        <span className="text-muted-foreground">
                          confidence {Number(t.confidence).toFixed(2)}
                        </span>
                      )}
                    </div>
                    <p className="mt-1 text-sm">{t.text}</p>
                    {t.latencyMs && (
                      <div className="text-[10px] text-muted-foreground mt-1">
                        latency {t.latencyMs}ms · cost ${((t.costMicros ?? 0) / 1_000_000).toFixed(5)}
                      </div>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>
    </AppShellServer>
  );
}
